### ISSUE TITLE
Error Inflating 

### ISSUE THREAD

**Issue by MSalaah96** [FinweLtd/orion360-sdk-pro-examples-android#5]
Unable to start activity ComponentInfo{com.example.salah.buiut/com.example.salah.buiut.Screens.Image360.MinimalImageDownloadPlayer}: android.view.InflateException: Binary XML file line #7: Binary XML file line #7: Error inflating class fi.finwe.orion360.OrionImageView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2779)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2844)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)

what should cause this problem ? !

**Comment by trantako** [comment]
Based on the crash log the issue has occurred on Basic version, not Pro.

Please post the issue to this repository instead and provide a code example, if possible:
https://github.com/FinweLtd/orion360-sdk-basic-examples-android
