### ISSUE TITLE
Fatal Exception: java.lang.IllegalThreadStateException

### ISSUE THREAD

**Issue by ImDroidGuy** [FinweLtd/orion360-sdk-pro-examples-android#6]
Fatal Exception: java.lang.IllegalThreadStateException: Thread already started
       at java.lang.Thread.checkNotStarted(Thread.java:849)
       at java.lang.Thread.start(Thread.java:1059)
       at fi.finwe.orion360.OrionVideoPlayerAsync.initializePlayer(OrionVideoPlayerAsync.java:108)
       at fi.finwe.orion360.OrionVideoView.onContextStatusChanged(OrionVideoView.java:579)
       at fi.finwe.orion360.OrionSurfaceView.onSurfaceChanged(OrionSurfaceView.java:477)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1520)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1248)

**DEVICE** : SAMSUNG GALAXY NOTE 3 
**OS** : 5

**Comment by trantako** [comment]
Based on the crash log the issue has occurred on Basic version, not Pro.

Please post the issue to this repository instead and provide a code example, if possible:
https://github.com/FinweLtd/orion360-sdk-basic-examples-android
